@HOST = {{$dotenv SERVER_URL}}/novel/
@IMG = {{$dotenv SERVER_URL}}/images/
###
GET {{IMG}}1667805673092_714619.png
###
GET {{HOST}}read?page=1&limit=5
###
GET {{HOST}}read/6381dc9f13d047620d85eddf
###
DELETE {{HOST}}delete/6381dc9f13d047620d85eddf